---
- name: Chrony asserts
  ansible.builtin.assert:
    that: base_chrony_sources | length > 0

- name: Install chrony
  ansible.builtin.apt:
    name: chrony
    state: present
    update_cache: true

- name: Remove ntp
  ansible.builtin.apt:
    name: ntp
    state: absent
    purge: true

- name: Disable systemd-timesyncd  # noqa ignore-errors
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: stopped
    masked: true
  ignore_errors: true

- name: Copy chrony config
  ansible.builtin.template:
    src: templates/chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: "0444"
  notify: Restart chronyd

- name: Start and enable chrony
  ansible.builtin.systemd:
    name: chrony
    state: started
    enabled: true
