- name: Clamav asserts
  ansible.builtin.assert:
    that:
      - base_clamav is boolean

- name: Install clamav
  when: base_clamav
  block:
  - name: Install clamav package
    ansible.builtin.apt:
      name: clamav
      state: present
      update_cache: true
    register: installed_clamav

  - name: Start and enable freshclam
    ansible.builtin.systemd:
      name: clamav-freshclam
      state: started
      enabled: true

  - name: Add clamscan cronjob
    ansible.builtin.lineinfile:
      path: /var/spool/cron/crontabs/root
      line: "{{ item }}"
    with_items: "{{ base_clamav_cronjobs }}"

- name: Uninstall clamav
  when: not base_clamav
  block:
  - name: Purge clamav services
    ansible.builtin.apt:
      name: "clamav"
      state: absent
      purge: true
      autoremove: true

  - name: Check for clamav logs
    ansible.builtin.stat:
      path: /var/log/clamav
    register: clamav_logs

  - name: Remove clamav logs
    ansible.builtin.file:
      path: /var/log/clamav
      state: absent
    when: clamav_logs.stat.exists

  - name: Confirm root has crontab
    ansible.builtin.stat:
      path: /var/spool/cron/crontabs/root
    register: root_crontab

  - name: Remove clamav cronjobs
    ansible.builtin.lineinfile:
      path: /var/spool/cron/crontabs/root
      regexp: "clamscan"
      state: absent
    when: root_crontab.stat.exists
