---
- name: Check asserts
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version in ["11", "12"]

- name: Package operations
  ansible.builtin.import_tasks: packages.yml
  tags: base_packages

- name: Configure unattended upgrades
  ansible.builtin.import_tasks: unattended_upgrades.yml
  when: base_unattended_upgrades
  tags: base_unattended_upgrades

- name: Fstab configuration
  ansible.builtin.import_tasks: fstab.yml
  tags: base_fstab

- name: Set timezone
  community.general.timezone:
    name: "{{ base_timezone | default('UTC') }}"
  tags: base_timezone

- name: Configure resolved
  ansible.builtin.template:
    src: templates/resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart resolved
  tags: base_resolved

- name: Configure chrony
  ansible.builtin.import_tasks: chrony.yml
  tags: base_chrony

- name: Configure auditd
  ansible.builtin.import_tasks: auditd.yml
  tags: base_auditd

- name: Configure postfix
  ansible.builtin.import_tasks: postfix.yml
  tags: base_postfix

- name: Configure aide
  ansible.builtin.import_tasks: aide.yml
  tags: base_aide

- name: Enforce apparmpr
  ansible.builtin.command:
    cmd: aa-enforce /etc/apparmor.d/*
  changed_when: false
  tags: base_apparmor

- name: Configure logrotate
  ansible.builtin.template:
    src: templates/logrotate.conf.j2
    dest: /etc/logrotate.conf
    owner: root
    group: root
    mode: "0644"
  tags: base_logrotate

- name: Disable coredumps
  ansible.builtin.copy:
    src: files/coredump.conf
    dest: /etc/systemd/coredump.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart server
  tags: base_disable_coredump

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
