---
- name: Check asserts
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version in ["11", "12"]

- name: Fstab configuration
  ansible.builtin.import_tasks: fstab.yml
  tags: base_fstab

- name: Disable coredumps
  ansible.builtin.copy:
    src: files/coredump.conf
    dest: /etc/systemd/coredump.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart server
  tags: base_disable_coredump

- name: Set timezone
  community.general.timezone:
    name: "{{ base_timezone | default('UTC') }}"
  tags: base_timezone

- name: Package operations
  ansible.builtin.import_tasks: packages.yml
  tags: base_packages

- name: Configure packages
  ansible.builtin.import_tasks: config.yml
  tags: base_config

- name: Custom scripts
  ansible.builtin.copy:
    src: files/chomp
    dest: /usr/local/bin/chomp
    owner: root
    group: root
    mode: "0755"
  tags: base_custom_scripts

- name: Enforce apparmpr
  ansible.builtin.command:
    cmd: aa-enforce /etc/apparmor.d/*
  changed_when: false
  tags: base_apparmor

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
