---
- name: Configure debian sources
  ansible.builtin.template:
    src: templates/sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: "0644"

- name: Update cache
  ansible.builtin.apt:
    update_cache: true

- name: Remove packages
  ansible.builtin.apt:
    name: "{{ removed_package }}"
    state: absent
  with_items: "{{ base_remove_packages }}"
  loop_control:
    loop_var: removed_package
  when:
    - base_remove_packages is defined
    - base_remove_packages | length > 0

- name: Install packages
  ansible.builtin.apt:
    name: "{{ installed_package }}"
    state: present
  with_items: "{{ base_install_packages }}"
  loop_control:
    loop_var: installed_package
  when:
    - base_install_packages is defined
    - base_install_packages | length > 0
