---
- name: Configure debian sources
  ansible.builtin.template:
    src: templates/sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: "0644"

- name: Update cache
  ansible.builtin.apt:
    update_cache: true

- name: Remove packages
  when:
    - base_remove_packages is defined
    - base_remove_packages | length > 0
  block:
    - name: Set_fact _base_remove_packages
      ansible.builtin.set_fact:
        _base_remove_packages: "{{ _base_remove_packages | default([]) + [package] }}"
      loop: "{{ base_remove_packages }}"
      loop_control:
        loop_var: package

    - name: Remove packages
      ansible.builtin.apt:
        name: "{{ _base_remove_packages }}"
        state: absent

- name: Install packages
  when:
    - base_install_packages is defined
    - base_install_packages | length > 0
  block:
    - name: Set_fact _base_install_packages
      ansible.builtin.set_fact:
        _base_install_packages: "{{ _base_install_packages | default([]) + [package] }}"
      loop: "{{ base_install_packages }}"
      loop_control:
        loop_var: package

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ _base_install_packages }}"
        state: present
