---
- name: Install postfix and mailx
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - postfix
    - bsd-mailx

- name: Start/enable postfix
  ansible.builtin.systemd:
    name: postfix
    state: started
    enabled: true

- name: Configure postfix
  notify: Restart postfix
  block:
    - name: Postfix only on localhost
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        regexp: "^inet_interfaces = .*"
        line: "inet_interfaces = loopback-only"

    - name: Postfix ipv4 only
      ansible.builtin.lineinfile:
        path: /etc/postfix/main.cf
        regexp: "^inet_protocols = .*"
        line: "inet_protocols = ipv4"
