- name: Confirm aide removal
  ansible.builtin.assert:
    that:
      - base_aide is false

- name: Purge aide
  ansible.builtin.apt:
    name: aide
    state: absent
    purge: true

- name: Remove logs
  ansible.builtin.file:
    path: /var/log/aide
    state: absent

- name: Remove cron file
  ansible.builtin.file:
    path: /etc/cron.weekly/aide
    state: absent
