- name: Confirm aide removal
  ansible.builtin.assert:
    that:
      - base_aide is false

- name: Purge aide
  ansible.builtin.apt:
    name: aide
    state: absent
    purge: true

- name: Remove logs and cron file
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/log/aide
    - /etc/cron.weekly/aide
