---
- name: Install resolved
  ansible.builtin.apt:
    name: systemd-resolved
    state: latest
    update_cache: true

- name: Start and enable resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: started
    enabled: true

- name: Configure resolved
  ansible.builtin.template:
    src: templates/resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart resolved
  tags: base_resolved

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
