- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
    update_cache: true

- name: Start and enable unattended-upgrades
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: started
    enabled: true

- name: Configure unattended upgrades
  ansible.builtin.copy:
    src: files/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"
  notify: Restart unattended-upgrades
  tags: base_unattended_upgrades
