---
- name: Enable unattended-upgrades
  when: base_unattended_upgrades
  block:
  - name: Install unattended-upgrades
    ansible.builtin.apt:
      name: unattended-upgrades
      state: present
      update_cache: true

  - name: Start and enable unattended-upgrades
    ansible.builtin.systemd:
      name: unattended-upgrades
      state: started
      enabled: true

  - name: Configure unattended upgrades
    ansible.builtin.template:
      src: templates/50unattended-upgrades.j2
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
      owner: root
      group: root
      mode: "0644"
    notify: Restart unattended-upgrades

- name: Disable unattended-upgrades
  when: not base_unattended_upgrades
  block:
  - name: Remove unattended-upgrades
    ansible.builtin.apt:
      name: unattended-upgrades
      state: absent
      autoremove: true

  - name: Remove unattended upgrades conf
    ansible.builtin.file:
      path: /etc/apt/apt.conf.d/50unattended-upgrades
      state: absent
