---
- name: Restart server
  ansible.builtin.reboot:
  when: base_allow_reboot | default(true)

- name: Restart postfix
  ansible.builtin.systemd:
    name: postfix
    state: restarted

- name: Restart auditd
  ansible.builtin.systemd:
    name: auditd
    state: restarted

- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Restart chronyd
  ansible.builtin.systemd:
    name: chrony
    state: restarted

- name: Restart unattended-upgrades
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: restarted

- name: Restart resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
