- name: Install chrony
  ansible.builtin.apt:
    name: chrony
    state: present

- name: Remove ntp
  ansible.builtin.apt:
    name: ntp
    state: absent
    purge: true

- name: Disable systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: stopped
    masked: true

- name: Start and enable chrony
  ansible.builtin.systemd:
    name: chrony
    state: started
    enabled: true
