- name: Clamav asserts
  ansible.builtin.assert:
    that:
      - base_freshclam_daemon is defined
      - base_freshclam_daemon is boolean
      - base_clamav_daemon is defined
      - base_clamav_daemon is boolean

- name: Install clamav
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - clamav
    - clamav-daemon
  register: installed_clamav

- name: Disable freshclam daemon
  ansible.builtin.systemd:
    name: clamav-freshclam
    state: stopped
    enabled: false
  register: disabled_freshclam
  when: not base_freshclam_daemon and installed_clamav.changed

- name: Disable clamd daemon
  ansible.builtin.systemd:
    name: clamav-daemon
    state: stopped
    enabled: false
  when: not base_freshclam_daemon

- name: Enable freshclam daemon
  ansible.builtin.systemd:
    name: clamav-freshclam
    state: started
    enabled: true
  when: base_freshclam_daemon

- name: Enable_clamd daemon
  ansible.builtin.systemd:
    name: clamav-daemon
    state: started
    enabled: true
  when: base_freshclam_daemon

- name: Kill freshclam if running
  ansible.builtin.shell:
    cmd: (pkill freshclam) || true
  changed_when: true
  when: disabled_freshclam.changed

- name: Update clamav databases
  ansible.builtin.command:
    cmd: /usr/bin/freshclam
  changed_when: true
  when: installed_clamav.changed

- name: Add clamscan cronjob
  ansible.builtin.lineinfile:
    path: /var/spool/cron/crontabs/root
    line: "{{ item }}"
  with_items:
    - "0 0 * * SUN /usr/bin/freshclam && /usr/bin/time nice -n19 /usr/bin/clamscan --exclude=/proc --exclude=/sys -ri /"
    - "0 0 * * WED /usr/bin/freshclam && /usr/bin/time nice -n19 /usr/bin/clamscan --exclude=/proc --exclude=/sys -ri /"

- name: Clamav user nologin
  ansible.builtin.command:
    cmd: usermod -s /usr/sbin/nologin clamav
  changed_when: false
