- name: Fail2ban asserts
  ansible.builtin.assert:
    that:
      - base_fail2ban_sshd_bantime is defined
      - base_fail2ban_sshd_findtime is defined
      - base_fail2ban_sshd_findtime is defined

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true

- name: Start and enable fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true

- name: Copy configuration
  ansible.builtin.template:
    src: templates/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0640"
  notify: Restart fail2ban
