---
- name: Check asserts
  ansible.builtin.assert:
    that:
      - base_timezone is defined

- name: Update packages
  ansible.builtin.apt:
    name: "*"
    update_cache: true
    state: latest
  tags: base_update_packages

- name: Check for reboot
  ansible.builtin.stat:
    path: /var/run/reboot-required
  notify: Restart server

- name: Configure unattended upgrades
  ansible.builtin.import_tasks: unattended_upgrades.yml
  tags: base_unattended_upgrades

- name: Fstab /tmp and /var/tmp
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "{{ item }}"
  loop:
    - "tmpfs   /tmp         tmpfs   rw,nodev,nosuid,noexec 0 0"
    - "tmpfs   /var/tmp         tmpfs   rw,nodev,nosuid,noexec 0 0"
  notify: Restart server
  tags: base_fstab

- name: Set timezone
  ansible.builtin.command:
    cmd: "timedatectl set-timezone {{ base_timezone }}"
  changed_when: false
  tags: base_timezone

- name: Remove packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    purge: true
  with_items: "{{ base_remove_packages }}"
  tags: base_remove_packages

- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ base_install_packages }}"
  tags: base_install_packages

- name: Configure chrony
  ansible.builtin.import_tasks: chrony.yml
  tags: base_chrony

- name: Configure cron
  ansible.builtin.import_tasks: cron.yml
  tags: base_cron

- name: Configure auditd
  ansible.builtin.import_tasks: auditd.yml
  tags: base_auditd

- name: Configure postfix
  ansible.builtin.import_tasks: postfix.yml
  tags: base_postfix

- name: Configure clamav
  ansible.builtin.import_tasks: clamav.yml
  tags: base_clamav

- name: Configure fail2ban
  ansible.builtin.import_tasks: fail2ban.yml
  tags: base_fail2ban

- name: Configure aide
  ansible.builtin.import_tasks: aide.yml
  tags: base_aide

- name: Enforce apparmpr
  ansible.builtin.command:
    cmd: aa-enforce /etc/apparmor.d/*
  changed_when: false
  tags: base_apparmor

- name: Disable coredumps
  ansible.builtin.import_tasks: coredump.yml
  tags: base_disable_coredump

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
