- hosts: all
  become: true
  tasks:
  - name: Update packages
    ansible.builtin.apt:
      name: "*"
      update_cache: true
      state: latest

  - name: Autoremove unneeded packages
    ansible.builtin.apt:
      autoremove: true

  - name: Check for reboot
    ansible.builtin.stat:
      path: /var/run/reboot-required
    notify: Restart server

  handlers:
  - name: Restart server
    ansible.builtin.reboot:
